Repository microsoft/pai, pull requests merged in 2018-06, with the labels that each got.

#663 Write password in stdin when ssh due to the need of sudo. And workaro…
  pai-management/k8sPaiLibrary/maintainlib/common.py
Labels: urgent

#688 Add single box deployment instruction in README
  pai-management/doc/cluster-bootup.md
  pai-management/doc/single-box-deployment.md
Labels: doc

#645 [Examples] Add TensorFlow serving example
  examples/serving/README.md
  examples/serving/serving.tensorflow.json
  rest-server/src/config/job.js
  rest-server/src/models/job.js
Labels: doc

#706 Update eslint command
  rest-server/package.json
  webportal/package.json
  webportal/src/app/job/job-submit/job-submit.component.js
  webportal/src/app/job/job-submit/job-submit.schema.js
  webportal/src/app/job/job-view/job-view.component.js
Labels: bug

#735 [Rest Server] Fix Docker container OOM issue
  rest-server/src/models/job.js
  rest-server/src/templates/dockerContainerScript.mustache
  rest-server/src/templates/yarnContainerScript.mustache
Labels: bug

#763 Update openpai examples
  examples/cntk/README.md
  examples/cntk/cntk.g2p.json
  examples/jupyter/README.md
  examples/jupyter/jupyter.json
  examples/keras/Dockerfile.example.keras.cntk_backend
  examples/keras/Dockerfile.example.keras.tensorflow_backend
  examples/keras/README.md
  examples/keras/keras.cntk_backend.mnist.json
  examples/keras/keras.tensorflow_backend.mnist.json
  examples/mpi/README.md
  examples/mpi/cntk-mpi.json
  examples/mpi/tensorflow-mpi.json
  examples/mxnet/README.md
  examples/mxnet/mxnet.autoencoder.json
  examples/mxnet/mxnet.image-classification.json
  examples/pytorch/README.md
  examples/pytorch/pytorch.mnist.json
  examples/pytorch/pytorch.regression.json
  examples/scikit-learn/README.md
  examples/scikit-learn/sklearn.mnist.json
  examples/scikit-learn/sklearn.text-vectorizers.json
  examples/serving/README.md
  examples/serving/serving.tensorflow.json
  examples/tensorflow/README.md
  examples/tensorflow/tensorflow.cifar10.json
  examples/tensorflow/tensorflow.distributed-cifar10.json
  examples/tensorflow/tensorflow.imagenet.json
  examples/tensorflow/tensorflow.tensorboard.json
Labels: doc
