Repository microsoft/pai, pull requests merged in 2019-10, with the labels that each got.

#3694 [Rest Server] Add node selector for user jobs in k8s
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3688 [Webportal] Hide grafana dashboard in k8s webportal
  src/webportal/src/app/layout/layout.component.js
Labels: PureK8S

#3696 [Rest Server] Fix total gpu number in job summary
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S, bug

#3687 [Rest Server] Exclude unready node resources in virtual cluster
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
Labels: PureK8S

#3699 Support null in framework completion policy
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/models/v2/job/runtime-env.js
  src/webportal/src/app/job-submission/components/task-role/completion-policy.jsx
  src/webportal/src/app/job-submission/models/completion.js
  src/webportal/src/app/job-submission/models/protocol-schema.js
Labels: PureK8S

#3695 clean ${PAI_WORK_DIR} before mv content to this folder
  src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
  src/kube-runtime/build/kube-runtime.dockerfile
  src/kube-runtime/src/init
Labels: PureK8S

#3719 [Rest Server] Fix apiserver requests in RBAC
  src/rest-server/deploy/rbac.yaml
  src/rest-server/deploy/stop.sh
  src/rest-server/src/config/launcher.js
  src/rest-server/src/config/vc.js
  src/rest-server/src/models/v2/job/index.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
Labels: PureK8S

#3729 Fix sshd issues in k8s runtime
  src/kube-runtime/src/plugins/ssh/sshd.sh
Labels: bug

#3736 Fix runtime bug: failed to finish init container due to rm failed
  src/kube-runtime/src/init
Labels: bug

#3739 Fix RBAC token and env for runtime barrier
  src/kube-runtime/src/init
  src/rest-server/deploy/rbac.yaml
Labels: PureK8S

#3742 [Rest Server] Add pod priority to support FIFO job scheduling
  src/rest-server/src/middlewares/v2/hived.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3751 [Rest Server] Simplify error message for long job name
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3766 [Rest Server] Update pod priority to priority class
  src/rest-server/deploy/rbac.yaml
  src/rest-server/src/config/launcher.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3771 [Rest Server] Decompress large framework
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3786 [Rest Server] Add task retry count for elastic jobs
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S
