Repository microsoft/pai, pull requests merged in 2019-09, with the labels that each got.

#3508 [Rest Server] Fix hdfs container directory permission issue
  src/rest-server/src/models/v2/job/yarn.js
Labels: bug

#3529 [Hotfix] Fix hdfs container directory permission issue
  src/rest-server/src/models/v2/job/yarn.js
Labels: bug

#3426 [RemoteDev] Support remote development
  contrib/remote-dev-tool/.env.template
  contrib/remote-dev-tool/.gitignore
  contrib/remote-dev-tool/README.md
  contrib/remote-dev-tool/conf/clusters.template
  contrib/remote-dev-tool/conf/exports.template
  contrib/remote-dev-tool/imgs/sshinfo.png
  contrib/remote-dev-tool/imgs/token.png
  contrib/remote-dev-tool/remote-dev-tool.py
Labels: new feature

#3435 Add service deployment for framework controller
  .gitattributes
  src/k8s-frameworkcontroller/deploy/delete.sh
  src/k8s-frameworkcontroller/deploy/k8s-frameworkcontroller.yaml.template
  src/k8s-frameworkcontroller/deploy/refresh.sh
  src/k8s-frameworkcontroller/deploy/service.yaml
  src/k8s-frameworkcontroller/deploy/start.sh
  src/k8s-frameworkcontroller/deploy/stop.sh
Labels: PureK8S

#3544 [Deployment] Fix error StatefulSet kind in template generation
  deployment/paiLibrary/paiService/service_template_generate.py
Labels: bug

#3528 [Deployment] Choose services for different cluster type
  deployment/paiLibrary/paiService/service_management_configuration.py
  deployment/paiLibrary/paiService/service_management_delete.py
  deployment/paiLibrary/paiService/service_management_refresh.py
  deployment/paiLibrary/paiService/service_management_start.py
  deployment/paiLibrary/paiService/service_management_stop.py
  src/alert-manager/deploy/service.yaml
  src/cleaner/deploy/service.yaml
  src/cluster-configuration/deploy/service.yaml
  src/drivers/deploy/service.yaml
  src/end-to-end-test/deploy/service.yaml
  src/grafana/deploy/service.yaml
  src/hadoop-batch-job/deploy/service.yaml
  src/hadoop-data-node/deploy/service.yaml
  src/hadoop-jobhistory/deploy/service.yaml
  src/hadoop-name-node/deploy/service.yaml
  src/hadoop-node-manager/deploy/service.yaml
  src/hadoop-resource-manager/deploy/service.yaml
  src/job-exporter/deploy/service.yaml
  src/k8s-dashboard/deploy/service.yaml
  src/log-manager/deploy/service.yaml
  src/node-exporter/deploy/service.yaml
  src/prometheus/deploy/service.yaml
  src/pylon/deploy/service.yaml
  src/rest-server/deploy/service.yaml
  src/watchdog/deploy/service.yaml
  src/webportal/deploy/service.yaml
  src/yarn-frameworklauncher/deploy/service.yaml
  src/zookeeper/deploy/service.yaml
Labels: PureK8S

#3548 [Rest Server] Fix legacy job router issue in k8s
  src/rest-server/src/routes/user.js
Labels: PureK8S, bug

#3577 [Deployment] Remove password from stdin in paictl
  deployment/k8sPaiLibrary/maintainlib/common.py
Labels: security

#3570 Fix some minor issue in API.md
  docs/rest-server/API.md
Labels: restserver

#3566 [Rest Server] Change PAI_JOB_NAME to framework name
  src/rest-server/src/models/v2/job/runtime-env.js
Labels: PureK8S

#3579 Fix rest server deployment issues in k8s
  src/hivedscheduler/deploy/start.sh
  src/rest-server/deploy/rest-server.yaml.template
  src/rest-server/deploy/service.yaml
Labels: PureK8S

#3569 [Examples] Update marketplace job to be compatible with k8s
  marketplace-v2/keras-tensorflow-mnist.yaml
  marketplace-v2/pytorch-mnist.yaml
  marketplace-v2/tensorflow-cifar10.yaml
Labels: PureK8S

#3568 [Examples] Add a horovod mpi example in marketplace
  marketplace-v2/horovod-pytorch-synthetic-benchmark.yaml
Labels: PureK8S

#3599 [Rest Server] Change to default k8s scheduler
  src/hivedscheduler/deploy/service.yaml
  src/hivedscheduler/deploy/start.sh.template
  src/hivedscheduler/deploy/stop.sh.template
  src/rest-server/deploy/rest-server.yaml.template
  src/rest-server/src/config/launcher.js
  src/rest-server/src/config/vc.js
  src/rest-server/src/controllers/v2/virtual-cluster.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
  src/rest-server/src/routes/v2/virtual-cluster.js
  src/webportal/src/app/home/home/conn.js
Labels: PureK8S

#3627 [Rest Server] Skip hived config mount in default scheduler
  src/rest-server/deploy/rest-server.yaml.template
Labels: PureK8S

#3575 Change rest-server to support errorSpec
  src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
  src/rest-server/deploy/configmap-create.sh.template
  src/rest-server/deploy/k8s-job-exit-spec-config/k8s-job-exit-spec.yaml.template
  src/rest-server/deploy/rest-server.yaml.template
  src/rest-server/deploy/service.yaml
  src/rest-server/deploy/stop.sh
  src/rest-server/src/models/v1/job/yarn.js
  src/rest-server/src/models/v2/job/k8s.js
  src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
Labels: PureK8S

#3638 [Rest Server] Fix total GPU number when there're invalid GPUs
  src/rest-server/src/config/vc.js
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
  src/rest-server/src/utils/k8sUtils.js
Labels: PureK8S

#3648 Remove drivers service in k8s cluster deployment
  src/drivers/deploy/service.yaml
Labels: PureK8S

#3642 [Rest Server] Add pod GPU number for default scheduler
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3650 [Rest Server] Add graceful deletion timeout in submission config
  src/rest-server/src/config/launcher.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3664 Foreground stop all frameworks
  src/frameworkcontroller/deploy/delete.sh
Labels: PureK8S

#3682 [Webportal] Fix react layout issue in non-admin home page
  src/webportal/src/app/layout/alerts.jsx
  src/webportal/src/app/layout/layout.component.js
Labels: bug

#3680 fix log url redirect issue
  src/pylon/deploy/pylon-config/location.conf.template
Labels: bug

#3683 [Rest Server] Enable fancy retry policy for elastic tasks
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S
