Repository microsoft/pai, pull requests merged in 2019-03, with the labels that each got.

#2256 Fix yarn container failed when docker container exited quickly.
  src/rest-server/src/templates/yarnContainerScript.mustache
Labels: bug

#2277 Pylon: fix double start query in yarn redirect
  src/pylon/src/nginx.conf.template
Labels: hotfix

#2352 Support nvidia-container-runtime for gpu isolation
  src/rest-server/src/templates/dockerContainerScript.mustache
  src/rest-server/src/templates/yarnContainerScript.mustache
Labels: bug

#2379 [Webpotal Plugin] Fix bugs
  contrib/submit-nfs-job/src/App/TensorflowDistributedJob.tsx
Labels: bug

#2391 [Webportal Plugin] Fix bugs
  contrib/submit-nfs-job/src/App/TensorflowSingleNodeJob.tsx
Labels: bug

#2392 [Webportal] Update new issue template
  src/webportal/src/app/layout/layout.component.ejs
Labels: bug

#2393 [Webportal] Add active sidebar menu in job list/detail pages
  src/webportal/src/app/job/job-view/fabric/job-detail.jsx
  src/webportal/src/app/job/job-view/fabric/job-list.jsx
Labels: bug

#2448 fix void env supply by yarnScript
  src/job-exporter/src/docker_inspect.py
  src/job-exporter/test/data/inspect_result_bug_fix.json
  src/job-exporter/test/test_docker_inspect.py
Labels: v0.11.0 needed
