Repository microsoft/pai, pull requests merged in 2019-12, with the labels that each got.

#3929 [VS Code] Fix add cluster bug when connection timeout
  contrib/pai_vscode/schemas/pai_cluster.schema.json
  contrib/pai_vscode/src/pai/clusterManager.ts
Labels: vs code extension

#3947 [Hotfix] Specify image pull policy for app container (#3933)
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3948 [Hotfix] Check resource quota for gang scheduling
  src/rest-server/src/middlewares/v2/hived.js
Labels: PureK8S

#3943 [Rest Server] Add image pull secrets for private registry
  src/rest-server/src/config/launcher.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3952 [Hotfix] Add image pull secrets for private registry (#3943)
  src/rest-server/src/config/launcher.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3953 [Hotfix] Add critical priority in hived (#3949)
  src/rest-server/src/middlewares/v2/hived.js
Labels: PureK8S

#3949 [Rest Server] Add critical priority in hived
  src/rest-server/src/middlewares/v2/hived.js
Labels: PureK8S

#3954 Fix vulnerabilities in npm dependencies
  contrib/marketplace/package.json
  contrib/marketplace/yarn.lock
  contrib/submit-job-v2/package.json
  contrib/submit-job-v2/yarn.lock
  contrib/submit-simple-job/package-lock.json
  src/rest-server/package.json
  src/rest-server/yarn.lock
  src/webportal/package.json
  src/webportal/yarn.lock
Labels: dependencies, javascript

#3940 [Rest Server] Add available resources for low priotity cluster
  src/rest-server/src/config/vc.js
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
  src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Labels: PureK8S

#3971 [Rest Server] Fix duplicate affinity group name issue
  src/rest-server/src/middlewares/v2/hived.js
  src/rest-server/src/middlewares/v2/protocol.js
Labels: PureK8S, bug

#3973 [Hotfix] Fix duplicate affinity group name issue (#3971)
  src/rest-server/src/middlewares/v2/hived.js
  src/rest-server/src/middlewares/v2/protocol.js
Labels: PureK8S

#3969 [VS Code] job V2 local simulation
  contrib/pai_vscode/package.json
  contrib/pai_vscode/src/pai/paiJobManager.ts
Labels: vs code extension

#3991 [VS Code] use bash in simulation
  contrib/pai_vscode/src/pai/paiJobManager.ts
Labels: vs code extension

#4011 [VS Code] Fix property is not allowed error
  contrib/pai_vscode/schemas/pai_yaml_job_config.schema.json
Labels: vs code extension

#4061 [VS Code] Fix submit job to https cluster
  contrib/pai_vscode/schemas/pai_cluster.schema.json
  contrib/pai_vscode/src/common/util.ts
  contrib/pai_vscode/src/pai/clusterManager.ts
  contrib/pai_vscode/src/pai/paiInterface.ts
  contrib/pai_vscode/src/pai/paiUri.ts
Labels: vs code extension

#4059 [CI/CD] Add Jenkins stages for pure k8s version
  Jenkinsfile
  tests/jenkins/stage_build.sh
  tests/jenkins/stage_clean.sh
  tests/jenkins/stage_deploy.sh
  tests/jenkins/stage_prepare.sh
  tests/jenkins/stage_test.sh
  tests/jenkins/test_generate_config.sh
  tests/jenkins/test_rest_server.sh
Labels: PureK8S

#4064 [VS Code] version 0.2.3 change log update
  contrib/pai_vscode/CHANGELOG.md
  contrib/pai_vscode/package.json
Labels: vs code extension

#4069 [Rest Server] Update job name encoding method
  docs/pai-job-protocol.yaml
  src/rest-server/package.json
  src/rest-server/src/config/v2/protocol.js
  src/rest-server/src/models/v2/job-attempt.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/yarn.lock
  src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
Labels: PureK8S
