Repository microsoft/pai, pull requests merged in 2019-07, with the labels that each got.

#3030 [Docs] Fix errors in job protocol example
  docs/pai-job-protocol.yaml
Labels: bug

#3024 [Rest Server] Add annotations in framework config
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3039 Integrate webportal with k8s rest server
  src/rest-server/src/controllers/v2/job.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/routes/v2/job.js
  src/webportal/src/app/home/home/conn.js
  src/webportal/src/app/job/job-submit/job-submit.component.js
  src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
  src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
  src/webportal/src/app/marketplace/job-submit/job-submit.component.js
Labels: PureK8S

#3053 [Rest Server] Adapt framework state and task state in k8s
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3071 [Rest Server] Use hex to encode and decode framework name
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3095 [Web Portal] change command section's default comments to placeholder
  src/webportal/config/webpack.common.js
  src/webportal/src/app/components/monaco-editor.jsx
  src/webportal/src/app/job-submission/components/command-section.jsx
  src/webportal/src/app/job-submission/components/monaco-text-field.jsx
  src/webportal/src/app/job-submission/components/tab-form.jsx
  src/webportal/src/app/job-submission/job-submission.jsx
  src/webportal/src/app/job-submission/models/job-task-role.js
  src/webportal/src/app/job-submission/utils/constants.js
Labels: 0.14.0

#3097 Binyli/docker
  src/webportal/src/app/job-submission/components/docker-section.jsx
  src/webportal/src/app/job-submission/models/job-task-role.js
  src/webportal/src/app/job-submission/models/protocol-schema.js
Labels: 0.14.0

#3098 add error message when command is empty
  src/webportal/src/app/job-submission/components/command-section.jsx
  src/webportal/src/app/job-submission/components/monaco-text-field.jsx
Labels: 0.14.0

#3101 change label of container size to resources per instance
  src/webportal/src/app/job-submission/components/container-size-section.jsx
Labels: 0.14.0

#3119 change to lowercase letter for 'Completion Policy'
  src/webportal/src/app/job-submission/components/task-role/completion-policy.jsx
Labels: 0.14.0

#3062 [purek8s] add hived field in job submission
  docs/pai-job-protocol.yaml
  src/rest-server/src/config/v2/protocol.js
  src/rest-server/src/middlewares/v2/protocol.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3143 [Hotfix] Fix AAD group in dedicated vc create/delete
  docs/tools/dedicated_vc.md
  src/tools/.gitignore
  src/tools/node_maintain.py
  src/tools/operator_wrapper/__init__.py
  src/tools/operator_wrapper/alert_operator.py
  src/tools/operator_wrapper/restserver_operator.py
  src/tools/operator_wrapper/yarn_operator.py
  src/tools/tests/test_node_maintain.py
Labels: 0.14.0

#3134 Binyli/bug fix
  src/webportal/src/app/job-submission/components/docker-section.jsx
  src/webportal/src/app/job-submission/components/submission-section.jsx
  src/webportal/src/app/job-submission/models/docker-info.js
  src/webportal/src/app/job-submission/models/job-task-role.js
  src/webportal/src/app/job-submission/utils/constants.js
  src/webportal/src/app/job-submission/utils/task-roles-manager.js
Labels: 0.14.0

#3149 Binyli/change get vc api
  src/webportal/src/app/job-submission/job-submission.jsx
  src/webportal/src/app/job-submission/utils/conn.js
Labels: 0.14.0

#3167 Support stop framework api in k8s rest server
  src/rest-server/src/controllers/v2/job.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/routes/v2/job.js
Labels: PureK8S

#3154 Add PAI env variables in init scripts
  src/kube-runtime/build/kube-runtime.dockerfile
  src/kube-runtime/src/entry
  src/kube-runtime/src/parse.py
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/models/v2/job/runtime-env.js
Labels: PureK8S

#3190 [Rest Server] Fix completion policy validation bugs in protocol
  contrib/python-sdk/examples/1-submit-and-query-via-command-line.ipynb
  marketplace-v2/caffe-mnist.yaml
  marketplace-v2/chainer-cifar.yaml
  marketplace-v2/keras-tensorflow-mnist.yaml
  marketplace-v2/mxnet-autoencoder.yaml
  marketplace-v2/pytorch-mnist.yaml
  marketplace-v2/pytorch-regression.yaml
  marketplace-v2/sklearn-text-vectorizers.yaml
  marketplace-v2/tensorflow-cifar10.yaml
  src/rest-server/src/config/v2/protocol.js
  src/rest-server/src/models/v2/job/yarn.js
  src/rest-server/test/protocolSecret.js
  src/rest-server/test/v2/protocol.js
Labels: bug

#3228 [Rest Server] Add stopped state
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3229 change webportal doc link
  docs/user/job_submission.md
  src/webportal/src/app/home/home/recent-job-list.jsx
  src/webportal/src/app/home/index/bottom.jsx
  src/webportal/src/app/job-submission/components/job-information.jsx
  src/webportal/src/app/job/job-docs/job-docs.component.ejs
Labels: 0.14.0

#3224 [Rest Server] Generate random ports for scheduling
  src/kube-runtime/src/parse.py
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3242 [Rest Server] Add completing state for job and tasks
  src/rest-server/src/models/v2/job/k8s.js
  src/webportal/src/app/components/status-badge.jsx
  src/webportal/src/app/components/util/job.js
  src/webportal/src/app/home/home/job-status.jsx
  src/webportal/src/app/job/job-view/fabric/job-detail/util.js
Labels: PureK8S

#3241 [Rest Server] Add container gpus in task detail
  src/rest-server/src/config/launcher.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#3233 [Rest Server] Use base32 to encode framework name
  src/rest-server/package.json
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/yarn.lock
Labels: PureK8S

#3259 [Kube Runtime] Add port conflict check
  src/kube-runtime/src/init.d/parse.py
  src/kube-runtime/src/runtime
  src/kube-runtime/src/runtime.d/port.py
  src/webportal/src/app/job/job-view/fabric/JobList/utils.js
Labels: PureK8S

#3256 [Web Portal] fix "view full log" link in job submission page
  src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
Labels: bug

#3252 [Rest Server] Fix auth file issue in protocol converter
  docs/rest-server/API.md
  src/rest-server/package.json
  src/rest-server/src/controllers/job.js
  src/rest-server/src/controllers/v2/job.js
  src/rest-server/src/models/v2/job/yarn.js
  src/rest-server/src/utils/converter.js
  src/rest-server/test/jobConfig.js
Labels: bug
