Repository microsoft/pai, pull requests merged in 2020-03, with the labels that each got.

#4257 [CI/CD] Fix Jenkins issue caused by downloading MNIST 403
  tests/jenkins/stage_prepare.sh
  tests/jenkins/test_rest_server.sh
Labels: CI/CD

#4234 [VS Code] 0.3.0 document update
  contrib/pai_vscode/CHANGELOG.md
  contrib/pai_vscode/CHANGELOG_zh_CN.md
  contrib/pai_vscode/README.md
  contrib/pai_vscode/README_zh_CN.md
  contrib/pai_vscode/assets/add_personal_storage.gif
  contrib/pai_vscode/assets/auto_completion_code_snippets.gif
  contrib/pai_vscode/assets/auto_completion_property.gif
  contrib/pai_vscode/assets/auto_completion_runtime_plugin_right_click.gif
  contrib/pai_vscode/assets/auto_completion_runtime_plugin_snippet.gif
  contrib/pai_vscode/assets/auto_completion_snippet_right_click.gif
  contrib/pai_vscode/assets/connect.gif
  contrib/pai_vscode/assets/create_job.gif
  contrib/pai_vscode/assets/create_job_config_command.gif
  contrib/pai_vscode/assets/create_job_config_double_click.gif
  contrib/pai_vscode/assets/create_job_config_right_click.gif
  contrib/pai_vscode/assets/install.png
  contrib/pai_vscode/assets/source_code_auto_upload.gif
  contrib/pai_vscode/assets/storage.gif
  contrib/pai_vscode/assets/storage_active_bar.gif
  contrib/pai_vscode/assets/storage_delete_file.gif
  contrib/pai_vscode/assets/storage_download_file.gif
  contrib/pai_vscode/assets/storage_new_folder.gif
  contrib/pai_vscode/assets/storage_remote_edit.gif
  contrib/pai_vscode/assets/storage_setup_auto_upload.gif
  contrib/pai_vscode/assets/storage_upload_file.gif
  contrib/pai_vscode/assets/submit.gif
  contrib/pai_vscode/assets/yaml_validation_incorrect_type.gif
  contrib/pai_vscode/documentation/edit_yaml_job_config.md
  contrib/pai_vscode/documentation/storage_explorer_and_auto_upload.md
  contrib/pai_vscode/documentation/submit_job.md
  contrib/pai_vscode/package.json
  contrib/pai_vscode/src/pai/clusterManager.ts
  contrib/pai_vscode/src/pai/container/storage/NfsTreeItem.ts
  contrib/pai_vscode/src/pai/container/storage/mountPointTreeItem.ts
  contrib/pai_vscode/src/pai/container/storage/personalStorageTreeItem.ts
  contrib/pai_vscode/src/pai/storage/nfsStorageManager.ts
Labels: vs code extension

#4157 [Rest Server] Refactor storage by leveraging persistent volumes
  contrib/storage_plugin/README.MD
  docs/setup-persistent-volumes-on-pai.md
  src/rest-server/docs/swagger.yaml
  src/rest-server/src/controllers/v2/storage-deprecated.js
  src/rest-server/src/controllers/v2/storage.js
  src/rest-server/src/controllers/v2/user.js
  src/rest-server/src/middlewares/cache.js
  src/rest-server/src/models/v2/group.js
  src/rest-server/src/models/v2/job/k8s.js
  src/rest-server/src/models/v2/storage.js
  src/rest-server/src/models/v2/user.js
  src/rest-server/src/routes/v2/index.js
  src/rest-server/src/routes/v2/storage-deprecated.js
  src/rest-server/src/routes/v2/storage.js
  src/rest-server/src/utils/dbUtil.js
  src/rest-server/src/utils/error.d.ts
  src/rest-server/src/utils/localCache.js
  src/rest-server/src/utils/manager/storage/crudK8sSecret.js
  src/rest-server/src/utils/manager/storage/crudUtil.js
  src/rest-server/src/utils/manager/storage/storage.js
  src/rest-server/src/utils/userSecret.js
  src/rest-server/test/k8sSecret.js
Labels: PureK8S

#4270 [Rest Server] Use list pods with label selector in getting job detail
  src/rest-server/src/models/kubernetes/kubernetes.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: restserver

#4279 [Rest Server] Remove list pods from getting job detail
  src/rest-server/src/models/v2/job/k8s.js
Labels: restserver

#4292 [Rest Server] Update RBAC rules for storage
  src/rest-server/deploy/rbac.yaml
Labels: PureK8S

#4328 Update default docker image list
  src/webportal/src/app/job-submission/utils/constants.js
Labels: 0.18, UI Improvement

#4334 [Rest Server] Enable priority class by default
  src/rest-server/config/rest-server.yaml
Labels: PureK8S
