Repository microsoft/pai, pull requests merged in 2020-04, with the labels that each got.

#4345 [CI] Update python to 3.8 for lint document
  .github/workflows/lint.yml
  .travis.yml
  src/utilities/doc_checker.py
Labels: CI/CD

#4329 [Rest Server] Update virtual cluster metrics using scheduler api
  src/rest-server/src/config/vc.js
  src/rest-server/src/middlewares/v2/hived.js
  src/rest-server/src/middlewares/v2/protocol.js
  src/rest-server/src/models/v2/virtual-cluster/k8s.js
  src/rest-server/src/utils/k8sUtils.js
  src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Labels: PureK8S

#4342 [Rest Server] Support CPU cell in hived scheduler
  src/rest-server/src/middlewares/v2/hived.js
Labels: PureK8S

#4362 [Rest Server] Change gpuType(s) to skuType(s)
  src/rest-server/src/config/v2/hived.js
  src/rest-server/src/config/vc.js
  src/rest-server/src/middlewares/v2/hived.js
Labels: PureK8S

#4400 [Rest Server] Fix log path length
  src/rest-server/src/config/v2/protocol.js
  src/rest-server/src/models/v2/job/k8s.js
Labels: PureK8S

#4406 fix swagger validation errors
  .travis.yml
  src/rest-server/docs/swagger.yaml
Labels: 0.18

#4404 validate rest server swagger
  .travis.yml
  src/rest-server/docs/swagger.yaml
Labels: 0.18

#4420 update api version to 2.0.0
  src/rest-server/docs/swagger.yaml
Labels: 0.18
